name: InstantBattle
version: 0.0.1
main: ch.bukkit.playground.InstantBattlePlugin
commands:
  instantop:
    description: instant battle op commands
    usage:
  instant:
    description: instant battle player commands
    usage:
  instantdebug:
    description: instant battle debug enabling
    usage:
