name: ServerTools
version: 0.0.1
main: ch.bukkit.playground.tools.ServerToolsPlugin
commands:

  servertoolsdebug:
    description: instant battle debug enabling
    usage:
  pl:
    description: instant battle debug enabling
    usage:
  plugins:
    description: instant battle debug enabling
    usage:
  visible:
      description: instant battle debug enabling
      usage:
  invisible:
      description: instant battle debug enabling
      usage:
  info:
      description: instant battle debug enabling
      usage:
  server:
      description: instant battle debug enabling
      usage:
  name:
      description: instant battle debug enabling
      usage:
